package com.ammad.billcalculator.presentation.theme

import androidx.compose.ui.graphics.Color

// Light theme — Lumina Flux
val LightPrimary = Color(0xFF00796B)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFB2DFDB)
val LightOnPrimaryContainer = Color(0xFF003734)
val LightSecondary = Color(0xFF455A64)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightTertiary = Color(0xFFFFA000)
val LightOnTertiary = Color(0xFF503D00)
val LightBackground = Color(0xFFFDF7FF)
val LightOnBackground = Color(0xFF1D1B20)
val LightSurface = Color(0xFFFDF7FF)
val LightOnSurface = Color(0xFF1D1B20)
val LightSurfaceVariant = Color(0xFFE6E0E9)
val LightOnSurfaceVariant = Color(0xFF494551)
val LightSurfaceContainerLow = Color(0xFFFFFFFF)
val LightSurfaceContainer = Color(0xFFF2ECF4)
val LightSurfaceContainerHigh = Color(0xFFECE6EE)
val LightOutline = Color(0xFF7A7582)
val LightOutlineVariant = Color(0xFFCBC4D2)
val LightError = Color(0xFFBA1A1A)
val LightOnError = Color(0xFFFFFFFF)
val LightErrorContainer = Color(0xFFFFDAD6)
val LightOnErrorContainer = Color(0xFF93000A)

// Dark theme — Lumina Flux
val DarkPrimary = Color(0xFF80CBC4)
val DarkOnPrimary = Color(0xFF003734)
val DarkPrimaryContainer = Color(0xFF005048)
val DarkOnPrimaryContainer = Color(0xFFB2DFDB)
val DarkSecondary = Color(0xFFB0BEC5)
val DarkOnSecondary = Color(0xFF22323A)
val DarkTertiary = Color(0xFFE7C365)
val DarkOnTertiary = Color(0xFF241A00)
val DarkBackground = Color(0xFF121212)
val DarkOnBackground = Color(0xFFE6E0E9)
val DarkSurface = Color(0xFF121212)
val DarkOnSurface = Color(0xFFE6E0E9)
val DarkSurfaceVariant = Color(0xFF49454F)
val DarkOnSurfaceVariant = Color(0xFFA19DA8)
val DarkSurfaceContainerLow = Color(0xFF1D1B20)
val DarkSurfaceContainer = Color(0xFF211F26)
val DarkSurfaceContainerHigh = Color(0xFF2B2930)
val DarkSurfaceContainerHighest = Color(0xFF36343B)
val DarkOutline = Color(0xFF938F99)
val DarkOutlineVariant = Color(0xFF49454F)
val DarkError = Color(0xFFF2B8B5)
val DarkOnError = Color(0xFF601410)
val DarkErrorContainer = Color(0xFF8C1D18)
val DarkOnErrorContainer = Color(0xFFFFDAD6)
